### ISSUE TITLE
[BUG] TYPO3 7.5 Compatibility

### ISSUE THREAD

**Issue by pvanhemmen** [pagemachine/hairu#10]
Hey there, FE Integration of hairu breaks on a TYPO3 7.5 Installation with the following error:

``` #1289386765: Could not analyse class:PAGEmachine\Hairu\Controller\AuthenticationController maybe not loaded or no autoloader?```

Integration was fully functional on TYPO3 7.4. Will investigate further, if there's anything I can to do help fixing please let me know.

**Comment by mbrodala** [comment]
Odd. Can you check the `composer/autoload_psr4.php` in your `vendor-dir`? What's your setup exactly?

**Comment by pvanhemmen** [comment]
There's no entry for hairu if that's what you'd expect there? Other than that it's got the usual entries. Can post them if you're interested.

The site I'm referring to was freshly set up with TYPO3 7.4 with hairu installed through the TER. After upgrading to 7.5 hairu was broken. Before upgrading I deactivated all 3rd party extensions (including hairu) and emptied all caches including the autoload/code cache, of course.

Apache/2.2.22 (Debian)
Mysql 5.5.44-0+deb7u1-log (Debian)
php 5.5 through FastCGI

Out of curiousity: Is registration of the Controller in hairu different from other extensions? I could not see any difference at first glance, so I really can't tell a reason why it's breaking. Or I'm missing something important that happened with 7.5 since I can't find anything in the changelogs. Thanx!

**Comment by thomaskieslich** [comment]
Change autoload i composer.json to psr-4, reinstall and all is fine ;-)
 "autoload": {
    "psr-4": {
      "PAGEmachine\\Hairu\\": "Classes/"
    }
  }

**Comment by mbrodala** [comment]
You are absolutely right, this is still legacy from the early Composer days in 6.2. ;-)

**Comment by thomaskieslich** [comment]
Perhaps this is interesting to:
https://wiki.typo3.org/TYPO3.CMS/Releases/7.5/Feature#Feature:_.2368700_-_Autoload_definition_can_be_provided_in_ext_emconf.php
This is the new recommended way to register classes for TYPO3. ;-)

**Comment by pvanhemmen** [comment]
Excellent! Thanx for the fix and the new knowledge!

**Comment by mbrodala** [comment]
@thomaskieslich That's an option if you don't have a `composer.json` what we do though. ;-)

**Comment by thomaskieslich** [comment]
My last Comment for this ;-) A deeper explantion: 
http://insight.helhum.io/post/130876393595/how-to-configure-class-loading-for-extensions-in
