### ISSUE TITLE
Login not working since 10.4.33

### ISSUE THREAD

**Issue by darthnorman** [pagemachine/hairu#104]
Since the latest TYPO3 version released today, this extension doesn't seem to work anymore on our end.
Login procedure will not succeed.

**Comment by Etmolf** [comment]
The login process now expects a hash of the transmitted storage folders from the field "pid" in the form "123,456,789@hmacvalueofpidlist".

Something like:

```php
$pidList = '123,456,789';
$pidValue = sprintf('%s@%s', $pidList, GeneralUtility::hmac($pidList, FrontendUserAuthentication::class));
$hiddenInput = '<input type="hidden" name="pid" value="'.$pidValue.'" />';
```

https://github.com/TYPO3-CMS/frontend/blob/62e1e2b77208eb1725ef1112c7e99400b4542d4c/Classes/Middleware/FrontendUserAuthenticator.php#L59
