### ISSUE TITLE
Redirect after login / logout?

### ISSUE THREAD

**Issue by DoHahn** [pagemachine/hairu#14]
Hey guys,

what do I need to do to redirect my users to a certain page after login / logout?

The plugin is on Page A,
Page B is the page that is being protected. Both pages are on the same level.

Right now after a login the Page A just reloads and the login form is displayed again with an error message. 
When I navigate to Page B manually, I see that I am logged in anyway.
 
I stumbled upon the 'redirect_url' in the ShowLoginForm template but this variable is always empty. There is a slot the handles redirects but I did not find a way to configure the redirect.

**Comment by mbrodala** [comment]
Yes, there is no plugin configuration field for this as in felogin but you can do one of these:

1. Pass `return_url` via GET parameter to the login page, you'll see it outputted in the field you've already seen.
2. Customize the template and output the desired `return_url`, e.g. via `<f:link.page/>`

Let me know if this works out for you.

**Comment by DoHahn** [comment]
Hello,

I was able to solve it by changing the value of the hidden input field as you suggested:

`<input type="hidden" name="redirect_url" value="{f:uri.page(pageUid: settings.redirect.afterLogin)}"/>`

Any plans to make this a feature?

**Comment by mbrodala** [comment]
What exactly? The plugin configuration field?

Anyways, I'll close this issue. Feel free to open a new one if you want to request a feature.
