### ISSUE TITLE
Overwrite Action

### ISSUE THREAD

**Issue by alobeejay** [pagemachine/hairu#15]
Hey,
I need to overwrite the action "startPasswordResetAction". Is that somehow possible?
I found the following typoscript code:

> config.tx_extbase {
>     objects {
>         Tx_Extbase_Configuration_ConfigurationManager {
>            className = Tx_MyExt_Configuration_ConfigurationManager
>         }
>      }
> }

But I am not really able to get anything to work with it.

**Comment by mbrodala** [comment]
What exactly is your issue, or why do you need to overwrite that method?

Your attempt is basically correct but you need to use the specific class names for this case:

```
config.tx_extbase {
  objects {
    PAGEmachine\Hairu\Controller\AuthenticationController {
      className = YourVendor\YourPackage\Controller\Hairu\AuthenticationController
    }
  }
}
```

In this case (and after flushing the general caches) the `YourVendor\YourPackage\Controller\Hairu\AuthenticationController` would be used instead allowing you to customize everything as desired. Be aware that everything non-public is subject to breakage on updates.

**Comment by alobeejay** [comment]
Thanks for the code and the super fast reply!

I need completely different functionality for the password reset function, so I thought to just overwrite this one action instead of creating a whole new extension. I need the function to provide the email adress and get an email with the username and password.
Do you think there would be an easier way to achieve this?

So the typoscript worked, thank you for that, and my controller looks like this:
`<?php
namespace XXX\XXX\Controller;

class LoginController extends \PAGEmachine\Hairu\Controller\AuthenticationController {

    /**
     * Start password reset
     *
     * @param string $username Username of a user
     * @return void
     *
     * @validate $username NotEmpty
     */
    public function startPasswordResetAction($username) {
        error_log('test');
    }
}`

But it doesn't seem to work. It looks like the startPasswordResetAction from the hairu plugin gets called after sending the ShowPasswordResetForm.

**Comment by mbrodala** [comment]
Maybe you can join [the TYPO3 slack](https://typo3.slack.com/messages/typo3-cms/) where we can figure out the problem quicker.

**Comment by alobeejay** [comment]
Took a while for my invitation, but now I'm set. What now?

So I changed code in the original startPasswordResetAction from the hairu extension and does not change a thing. So I don't think this action is actually called.
But the form action in ShowPasswordResetAction.html the says
```
<f:form
      action="startPasswordReset"
      class="password-reset form-inline">
```

**Comment by mbrodala** [comment]
Please join the mentione channel so we can figure things out. :-)

**Comment by alobeejay** [comment]
It works now. Thank you very much for your help!

In case anybody else stumbles upon this:
startPasswordResetAction is only being called when the username check succeeds, when a frontend user with this name exists. I wanted to check a different field for this and could use 
`plugin.tx_hairu.mvc.validation.Authentication.startPasswordReset.username.1.options.property = email`
With that I could successfully overwrite the startPasswordResetAction in my own controller.
