### ISSUE TITLE
Signal Slots afterLogin and afterLogout not usable when using redirects

### ISSUE THREAD

**Issue by artisticMink** [pagemachine/hairu#16]
When a post-login/logout redirect is set either by typoscript or as url parameter, the redirect gets processed in the first slot of the corresponding signals. Cancelling script execution and therefore prohibiting any following slots to be executed. 

Having a slot to connect to before any redirect action takes place would be neat.

**Comment by mbrodala** [comment]
I see the problem but unfortunately no easy solution ATM.

I have proposed a [feature which allows for disconnecting slots from signals](https://review.typo3.org/46691) which could help here. With this you could unregister the shipped `RedirectUrlSlot`, add your own and re-add it again afterwards if desired. That change however is still in review.

What actions are you trying to perform at these points?

To have a working solution for now you could try this in your TypoScript setup:

```
config.tx_extbase {
  objects {
    PAGEmachine\Hairu\Slots\RedirectUrlSlot.className = Your\Custom\RedirectUrlSlot
  }
}
```

This would allow you to override the behavior of the `RedirectUrlSlot` to perform actions before the redirect occurs.

**Comment by artisticMink** [comment]
I'm doing some session housekeeping. 

Thanks for the advice, i implemented the class override like you suggested. Works fine enough and i don't have to get personal with any hairu files. 

Thanks again for the quick response.
