### ISSUE TITLE
No possibility to login into a service using the hairu when new user was tried to password recovery without profile activation

### ISSUE THREAD

**Issue by alorotom** [pagemachine/hairu#17]
1. A visitor was registered by 'femenager' extension and was not trying to login into a service using 'hairu'
2. The visitor trying to recovery of their password using 'hairu' and was set a new password
3. The visitor was tryed to login into the service using the new password and has no possibility to do it

Could you please help with the problem?

**Comment by mbrodala** [comment]
Can you please ask questions in https://typo3.slack.com/messages/typo3-cms/ instead? This is an issue tracker and right now I do not see an issue in our extension. If a real issue lies in our extension, feel free to open a new ticket.
