### ISSUE TITLE
Reducing the cooldown between warnings that you're not registered

### ISSUE THREAD

**Issue by Syvered** [pagemachine/hairu#18]
I'd like to know if there's a way I can reduce the amount of messages that are displayed when a user joins the server but doesn't login.

Its kinda over-spamming the chat with it.

**Comment by mbrodala** [comment]
Honestly I have no idea what you are talking about. :-) Are you sure you didn't post this to the wrong issue tracker?

**Comment by mbrodala** [comment]
OK, I may have an idea. I guess you are talking about the 5 second waiting time after a failed login attempt? That's a default behavior of TYPO3, if you want to change this you need to [implement a hook](https://docs.typo3.org/typo3cms/extensions/core/7.6/singlehtml/#feature-59231-hook-for-abstractuserauthentication-checkauthentication).

Notice however, that this is meant to tackle brute force attacks so make sure to not lower the security provided by the default behavior.
