### ISSUE TITLE
Signal for "startPasswordResetAction" (and maybe others?)

### ISSUE THREAD

**Issue by romaincanon** [pagemachine/hairu#2]
I would need a Signal in PAGEmachine\Hairu\Controller\AuthenticationController->startPasswordResetAction; I will have to send a custom mail, I would like to cancel the default one, and have a signal with the whole data (user, hash, etc.) to send my own one. Would it be possible to add one?

About the mail cancelation, I don't know what would be the best way to do it. I think you will find a solution by yourself, but I am open for a discussion about it. :-)

I also think you could add other signal for further usage, but that is not the main goal of this ticket. ;-)

Thanks!

**Comment by mbrodala** [comment]
Just to be sure: you basically want to implement a custom mail template? You can do this easily by extending `plugin.tx_hairu.view.templateRootPaths` and adding your own `PasswordResetMail.txt` and `PasswordResetMail.html` template files.

Is there something else you want to do different from the default mail setup?

**Comment by romaincanon** [comment]
No not really, I know how to change the template, but that's not what I need. :)

The thing is, I need to create a custom module for a customer, to allow him to create mail records: he then can chose an event ("user registration", "user connexion", "password reset", but also "page creation" or other things like this), the mail's receiver(s) and write his own mail title and body.

To do this correctly I need to use hooks and signals already implemented in the tools I use.

Do you need more explanation or is it clear enough?

Thanks!

**Comment by mbrodala** [comment]
So instead of customizing mail content (via template) and mail subject (via translations) you need full customization of the outgoing mail.

How about a new `beforePasswordResetMailSend` signal which is passed the prepared `MailMessage` instance? You could then override all properties of the message in your slot as necessary.

**Comment by romaincanon** [comment]
That would be really great. :)

**Comment by mbrodala** [comment]
Just added the signal as requested, it'd be great if you could test this before the next release. :-)

**Comment by typo360** [comment]
I just remembered I did not thank you for this. So here it is: it's working just fine, thanks a lot! ;-)

**Comment by romaincanon** [comment]
I just remembered I did not thank you for this. So here it is: it's working just fine, thanks a lot! ;-)
