### ISSUE TITLE
stdWrap.lang on reset mail subject is not working

### ISSUE THREAD

**Issue by mediaessenz** [pagemachine/hairu#28]
If I try to use the stdWrap method "lang" on the mail subject I only get "Array" as mail subject:
```
plugin.tx_hairu.settings.passwordReset.mail.subject.stdWrap.lang {
                    de = Passwort zurücksetzen
                    fr = Réinitialiser le mot de passe
                }
```
The Readme.md says this:
"You can also use the stdWrap property on any settings value for custom processing."

As far as I understand, stdWrap includes all this:
https://docs.typo3.org/typo3cms/TyposcriptReference/Functions/Stdwrap/Index.html

**Comment by mbrodala** [comment]
Thanks for reporting. I was easily able to reproduce this and added a fix. Can you verify that it also works for you with the latest master?
