### ISSUE TITLE
Redirect at the end of "startPasswordResetAction"

### ISSUE THREAD

**Issue by romaincanon** [pagemachine/hairu#3]
I am having some issues in PAGEmachine\Hairu\Controller\AuthenticationController->startPasswordResetAction: when the mail is sent, you call a redirect.

 I understand the need for this, but this is kind of buggy when using an Ajax call, as it calls a whole new page. I replaced with "forward" to test, and everything goes well after that.

I guess you used a redirect to prevent the form being submitted again after a page refresh, so I think you could not just replace by a forward?

Could we discuss on that?

**Comment by mbrodala** [comment]
Yes, the redirect is here to ensure submitted form data is dropped.

What issue exactly do you encounter in your AJAX flow? Loading a new page should not be an issue if you grab the relevant messages from the final page and show it to the user.

**Comment by romaincanon** [comment]
Well I'm not really a pro of JavaScript and Ajax usage, so I guess I'm doing things wrong.

In fact, I call your controller with Ajax, but when it ends, a redirection is made, so my JavaScript gets back the entire webpage of the site, not only the action's view.

An idea on how to manage this?

**Comment by mbrodala** [comment]
Usually requesting the full target page via AJAX and then only using parts of it works quite well so you must be doing something special here. Now it depends on what exactly you are doing to submit the form via AJAX and process the response.

**Comment by romaincanon** [comment]
Well instead of getting the full website in the Ajax response, I'd prefer to get the connexion or the forgot-password view, with the flash message ("an email has been sent [...]").

Any idea?

**Comment by mbrodala** [comment]
Maybe [helhum/typoscript_rendering](https://github.com/helhum/typoscript_rendering) is useful here to retrieve only the plugin content element.

**Comment by mbrodala** [comment]
@romaincanon Got something working?

**Comment by romaincanon** [comment]
Well I had no more time for this subject, so I used a hook that die() the page with my message.
Really dirty but I had to get something working asap.

I hope I will have some time one day to get back on this, but well... I don't think so. :-/

Thanks for the update!

**Comment by mbrodala** [comment]
Cleaning up, please post a new issue if there's something we can do.
