### ISSUE TITLE
Plaintext part of mail does not work in TYPO3 v8 LTS

### ISSUE THREAD

**Issue by pkerling** [pagemachine/hairu#30]
In TYPO3 v8 LTS, this: https://github.com/pagemachine/hairu/blob/25282d3/Classes/Controller/AuthenticationController.php#L281 does not seem to work any more. It will render the HTML template anyway (twice then).

Workaround could be to do `$this->view->getRenderingContext()->getTemplatePaths()->setFormat('txt')`, which does work for me.

But I'm not sure "abusing" the current view to render the mail template is the clean solution either way. It might be better to just use `StandaloneView`. It got a lot easier to use with v8 and the introduction of `TemplatePaths`.

**Comment by mbrodala** [comment]
I'll have a look at this. Notice that we still support TYPO3v7 so we cannot yet fully use v8 features.

**Comment by pkerling** [comment]
Yes, I know. It might be possible to use `StandaloneView` and include two code paths for setting it up, one for v7 (manually) and one for v8 (with `TemplatePaths`).
