### ISSUE TITLE
breaking change ValidFrontendUserValidator deleted

### ISSUE THREAD

**Issue by meisterkaiser** [pagemachine/hairu#43]
Hi,

commit 2f86a708e903db0df580d3a10febf33f16d51ad7 "Drop obsolete validator" the 
ValidFrontendUserValidator
class file was deleted.

As this is a potential breaking change (it broke pw reset on our system) I think this should not have been released on a patch level?

Manually uploading the missing file quickly fixes the immediate issue of course.
Why was it flagged as obsolete in the first place though? 
Did we miss a breaking change announcement or was the validator flagged as deprecated for some time?

Can you shed some light? Thx ...

**Comment by mbrodala** [comment]
Since https://github.com/pagemachine/hairu/commit/2cad7e224a0c69b2340fe8f139fb0ac80c884c00 this validator is not used anymore, so it was dropped. What does your error look like? Did you flush caches once?

**Comment by meisterkaiser** [comment]
I see...
Not a bug in the extension as such, still a potential breaking change for installations that override the default configuration (as does our installation), the deleted validator class will after an update to 2.1.2 still be configured in typoscript outside hairu.

Problem shows as "Argument 1 passed to TYPO3\CMS\Extbase\Validation\Validator\AbstractCompositeValidator::addValidator() must implement interface TYPO3\CMS\Extbase\Validation\Validator\ValidatorInterface, null given" in t3 log.

Easy fix now, thanks for the information!

Where would we find info on future config / breaking changes?
Maybe I was not looking hard enough, but couldn't find Release Notes in the repo, wiki or extension manual?
In charge of several installations with 15+ 3d party extensions its impossible to work through all commits after every composer update...

**Comment by mbrodala** [comment]
I am not sure how your configuration looked like since the removal of the validator should not have affected your customizations. Unless you have copied the full TypoScript which you should never do anyways.

Due to the low impact this change wasn't really seen as breaking but I can see now that there are edge cases I didn't see. I'll restore and deprecate the validator.

**Comment by mbrodala** [comment]
As for your question you'll find a small changelog here: https://github.com/pagemachine/hairu/releases

And obviously breaking changes will lead to a major version bump since we adhere to semver.

**Comment by meisterkaiser** [comment]
definitely edge case and yes, our configuration override was not ideal as well.
Anyway - thanks for quick info & solutions.

**Comment by mbrodala** [comment]
This has been released with version 2.1.3 (soon in TER), sorry for the inconvenience.
