### ISSUE TITLE
translation error?

### ISSUE THREAD

**Issue by sevensix** [pagemachine/hairu#45]
When i update the Language in typo3 8.7xx the flashmessages of the login.fail.messages don't get transated.  the languagefile seems a bit messy there (\typo3conf\l10n\de\hairu\Resources\Private\Language\de.locallang.xlf ). the target-Tag is closed immediately then opened again. if i manually fix that in that file, all is ok. so please fix this, to use the translation (here german) thx: 

```
<trans-unit id="login.failed.title">
        <source>Login failure</source>
      <target></target><alt-trans xml:space="preserve" origin="pkerling"><target>Anmeldung fehlgeschlagen</target></alt-trans></trans-unit>

```

 ```
<trans-unit id="login.failed.message">
        <source>Most likely you didn't enter the username or password correctly. Be certain that you enter them precisely as they are, including upper/lower case. Another possibility is that cookies might be disabled in your web browser.</source>
      <target></target><alt-trans xml:space="preserve" origin="pkerling"><target>Höchstwahrscheinlich wurden Benutzername oder Passwort falsch eingegeben.Bitte vergewissern Sie sich, dass diese Angaben korrekt sind, inklusive Groß- und Kleinschreibung. Außerdem könnten Cookies in Ihrem Browser deaktiviert sein.</target></alt-trans></trans-unit>

```

**Comment by mbrodala** [comment]
Thank you for bringing this up. I've just accepted the pending suggestions on the [TYPO3 translation server](https://translation.typo3.org/de/TYPO3.ext.hairu/) which included these two strings. You should be able to pull the updated translations soon.
