### ISSUE TITLE
should have:  Choosing Login.page in Flexform

### ISSUE THREAD

**Issue by sevensix** [pagemachine/hairu#49]
At the moment i only can set the login.page via constants, right? it would be better, if we could set the login.page for the plugin via flexform when we need to change the default loginpage. so we could choose if the plugin uses the default value or the specific one to rediect to a page after login.

**Comment by mbrodala** [comment]
I understand the usecase but I'm a bit reluctant to add a FlexForm. Normally it causes a few headaches when setting and unsetting an option since the empty FlexForm option overwrites the matching TypoScript option.

Are not able to solve this with TypoScript?

**Comment by sevensix** [comment]
Thanx. My editors should set the target redirect page via plugin/flexform) and should not go into TS-Setup... I implemented a Flexform into your extension my self. Now i can set the redirect via flexform (and use a f:if statement inside the template to check if a pid is set via flexform, if not the default redirect is taken). With this solution I also can have two Authplugins in one page with different redirect-targets (what I actually needed too). thx for your reply.

**Comment by mbrodala** [comment]
Glad you got it resolved. :-)
