### ISSUE TITLE
Reset fe_user sessions on password change

### ISSUE THREAD

**Issue by justusmoroni** [pagemachine/hairu#51]
The core had a security improvement for the fe_login extension.

The extension fe_login now destroys the sessions of the fe_user when the password for this user is changed.

The core team advises that the developers of extensions which handle password changes add changes like the core did to the extensions:
https://typo3.org/security/advisory/typo3-core-sa-2019-011/

https://docs.typo3.org/typo3cms/extensions/core/latest/Changelog/8.7.x/Important-87298-DestroySessionsOnPasswordChange.html

**Comment by mbrodala** [comment]
Sorry for the delay. This has been integrated and released with version 3.0.2 now.
