### ISSUE TITLE
reset password From name

### ISSUE THREAD

**Issue by davdenic** [pagemachine/hairu#53]
Hello
it would be nice if it could possible to set the From name in the reset password.
Thanks

**Comment by mbrodala** [comment]
You can already do this through the [`plugin.tx_hairu.settings.passwordReset.mail.from` TypoScript constant](https://github.com/pagemachine/hairu/blob/13a33c4539908d053b5e9b153908e65d9482f4a4/Configuration/TypoScript/setup.typoscript#L48). Did you do this?

**Comment by davdenic** [comment]
i can set only the from email but i want the from name and email like the email comes from
"My Company <info@mycompany.com>"

**Comment by mbrodala** [comment]
Did you configure `$GLOBALS['TYPO3_CONF_VARS']['MAIL']['defaultMailFromAddress']`? If you don't use the mentioned constant to set `from` then this will be used as fallback.

**Comment by davdenic** [comment]
Hi, i've tested now and the from name does not come out. just the from email address.
Thanks

**Comment by mbrodala** [comment]
Ah sorry, I just properly understood this ticket. It's not about the `From` feature in general but having a readable name in addition.

**Comment by davdenic** [comment]
Yes exactly.
Thanks

**Comment by mbrodala** [comment]
This was added with #54 now and will be part of the next release.

The `passwordReset.mail.from` setting can now look like this:

* `Foo Bar <foo@example.org>`
* `"Special.Characters.Need.Quotes" <special@example.com>`

Notice the 2nd case which is necessary to comply with [RFC 822](https://www.w3.org/Protocols/rfc822/#z8).
