### ISSUE TITLE
[BUGFIX] isUserAuthenticated in TYPO3 v10

### ISSUE THREAD

**Issue by fjacobi** [pagemachine/hairu#57]
Hej,
not sure if this solution is the best, but it worked in my current setup.

hairu/Classes/Domain/Service/AuthenticationService.php

```    /**
     * Returns whether any user is currently authenticated
     *
     * @return bool
     */
    public function isUserAuthenticated(): bool
    {
        $context = GeneralUtility::makeInstance(Context::class);
        return $context->getPropertyFromAspect('frontend.user', 'isLoggedIn');
    }
```

1) Not sure if bool should be used here, since the aspect has a defined return of mixed|null
2) Are contexts the way to go here or is it preferred to work closer along the internal API?

**Comment by mbrodala** [comment]
We should cast the result to `(bool)` in any case. The `mixed|null` type hint is based on the generic nature of the `getPropertyFromAspect()` API.

In any case yes, this is the way to go.

**Comment by fjacobi** [comment]
Okay, PR will follow soon.
