### ISSUE TITLE
TypeError in AbstractAuthenticationFormViewHelper

### ISSUE THREAD

**Issue by bjo3rnf** [pagemachine/hairu#72]
Hi,

I have an issue with hairu 3.1 after upgrading to TYPO3 10.4 because `UriBuilder` expects an int for the pageUid argument. The value taken from TypoScript settings/constants is a numeric string leading to a `TypeError`. A simple fix for me is to typecast the argument like `[...]->setTargetPageUid((int)$this->arguments['pageUid'])`. Is this something that needs to be adjusted in the viewhelper or am I doing something wrong?

Thanks in advance.

Cheers
Björn

**Comment by bjo3rnf** [comment]
Never mind. Since TYPO3 10.4 my use case is completely covered by core. Thank you.

**Comment by mbrodala** [comment]
I'll still have a look.

**Comment by Moongazer** [comment]
I can confirm this issue in v10.4.9, unfortunately my use-case is not covered by core^^ A simple `intval()` solves the problem.

**Comment by mbrodala** [comment]
@Moongazer Can you prepare a PR?

**Comment by Moongazer** [comment]
Here you go #77
